apiVersion: v1
kind: Namespace
metadata:
  name: ns-alpha
  labels:
    environment: staging
    team: platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-beta
  labels:
    environment: production
    team: platform
    istio-injection: enabled
